name: App wach halten
on:
  schedule:
    - cron: '0 */10 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Website aufrufen
        run: curl -s https://warum-wissen-wir-was-wir-wissen.streamlit.app/ > /dev/null
